[[redirects]]
from = "/old-path"
to = "/new-path"
status = 301

[[redirects]]
from = "/another-old-path"
to = "/another-new-path"
status = 301

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
